DB_PORT = 3306
DB_NAME = "novelty"
DB_USER = "ryan"
DB_PASSWORD = "Ps20010510"
SQL_DEBUG = "TRUE"
DB_HOST = "rm-rj97tt8j8pyecufjg4o.mysql.rds.aliyuncs.com"
db_table = "main_table"
completion_url = "https://app.prolific.com/submissions/complete?cc=C13H330O"

